sudo: required

services:
  - docker

env:
  - POSTGRESQL_VERSION=9.0.0
  - POSTGRESQL_VERSION=9.0.1
  - POSTGRESQL_VERSION=9.0.2
  - POSTGRESQL_VERSION=9.0.3
  - POSTGRESQL_VERSION=9.0.4
  - POSTGRESQL_VERSION=9.0.5
  - POSTGRESQL_VERSION=9.0.6
  - POSTGRESQL_VERSION=9.0.7
  - POSTGRESQL_VERSION=9.0.8
  - POSTGRESQL_VERSION=9.0.9
  - POSTGRESQL_VERSION=9.0.10
  - POSTGRESQL_VERSION=9.0.11
  - POSTGRESQL_VERSION=9.0.12
  - POSTGRESQL_VERSION=9.0.13
  - POSTGRESQL_VERSION=9.0.14
  - POSTGRESQL_VERSION=9.0.15
  - POSTGRESQL_VERSION=9.0.16
  - POSTGRESQL_VERSION=9.0.17
  - POSTGRESQL_VERSION=9.0.18
  - POSTGRESQL_VERSION=9.0.19
  - POSTGRESQL_VERSION=9.0.20
  - POSTGRESQL_VERSION=9.0.21
  - POSTGRESQL_VERSION=9.0.22
  - POSTGRESQL_VERSION=9.0.23 LATEST_MINOR=9.0

  - POSTGRESQL_VERSION=9.1.0
  - POSTGRESQL_VERSION=9.1.1
  - POSTGRESQL_VERSION=9.1.2
  - POSTGRESQL_VERSION=9.1.3
  - POSTGRESQL_VERSION=9.1.4
  - POSTGRESQL_VERSION=9.1.5
  - POSTGRESQL_VERSION=9.1.6
  - POSTGRESQL_VERSION=9.1.7
  - POSTGRESQL_VERSION=9.1.8
  - POSTGRESQL_VERSION=9.1.9
  - POSTGRESQL_VERSION=9.1.10
  - POSTGRESQL_VERSION=9.1.11
  - POSTGRESQL_VERSION=9.1.12
  - POSTGRESQL_VERSION=9.1.13
  - POSTGRESQL_VERSION=9.1.14
  - POSTGRESQL_VERSION=9.1.15
  - POSTGRESQL_VERSION=9.1.16
  - POSTGRESQL_VERSION=9.1.17
  - POSTGRESQL_VERSION=9.1.18
  - POSTGRESQL_VERSION=9.1.19
  - POSTGRESQL_VERSION=9.1.20
  - POSTGRESQL_VERSION=9.1.21
  - POSTGRESQL_VERSION=9.1.22
  - POSTGRESQL_VERSION=9.1.23
  - POSTGRESQL_VERSION=9.1.24 LATEST_MINOR=9.1

  - POSTGRESQL_VERSION=9.2.0
  - POSTGRESQL_VERSION=9.2.1
  - POSTGRESQL_VERSION=9.2.2
  - POSTGRESQL_VERSION=9.2.3
  - POSTGRESQL_VERSION=9.2.4
  - POSTGRESQL_VERSION=9.2.5
  - POSTGRESQL_VERSION=9.2.6
  - POSTGRESQL_VERSION=9.2.7
  - POSTGRESQL_VERSION=9.2.8
  - POSTGRESQL_VERSION=9.2.9
  - POSTGRESQL_VERSION=9.2.10
  - POSTGRESQL_VERSION=9.2.11
  - POSTGRESQL_VERSION=9.2.12
  - POSTGRESQL_VERSION=9.2.13
  - POSTGRESQL_VERSION=9.2.14
  - POSTGRESQL_VERSION=9.2.15
  - POSTGRESQL_VERSION=9.2.16
  - POSTGRESQL_VERSION=9.2.17
  - POSTGRESQL_VERSION=9.2.18
  - POSTGRESQL_VERSION=9.2.19 LATEST_MINOR=9.2

  - POSTGRESQL_VERSION=9.3.0
  - POSTGRESQL_VERSION=9.3.1
  - POSTGRESQL_VERSION=9.3.2
  - POSTGRESQL_VERSION=9.3.3
  - POSTGRESQL_VERSION=9.3.4
  - POSTGRESQL_VERSION=9.3.5
  - POSTGRESQL_VERSION=9.3.6
  - POSTGRESQL_VERSION=9.3.7
  - POSTGRESQL_VERSION=9.3.8
  - POSTGRESQL_VERSION=9.3.9
  - POSTGRESQL_VERSION=9.3.10
  - POSTGRESQL_VERSION=9.3.11
  - POSTGRESQL_VERSION=9.3.12
  - POSTGRESQL_VERSION=9.3.13
  - POSTGRESQL_VERSION=9.3.14
  - POSTGRESQL_VERSION=9.3.15 LATEST_MINOR=9.3

  - POSTGRESQL_VERSION=9.4.0
  - POSTGRESQL_VERSION=9.4.1
  - POSTGRESQL_VERSION=9.4.2
  - POSTGRESQL_VERSION=9.4.3
  - POSTGRESQL_VERSION=9.4.4
  - POSTGRESQL_VERSION=9.4.5
  - POSTGRESQL_VERSION=9.4.6
  - POSTGRESQL_VERSION=9.4.7
  - POSTGRESQL_VERSION=9.4.8
  - POSTGRESQL_VERSION=9.4.9
  - POSTGRESQL_VERSION=9.4.10 LATEST_MINOR=9.4

  - POSTGRESQL_VERSION=9.5.0
  - POSTGRESQL_VERSION=9.5.1
  - POSTGRESQL_VERSION=9.5.2
  - POSTGRESQL_VERSION=9.5.3
  - POSTGRESQL_VERSION=9.5.4
  - POSTGRESQL_VERSION=9.5.5 LATEST_MINOR=9.5

  - POSTGRESQL_VERSION=9.6.0
  - POSTGRESQL_VERSION=9.6.1 LATEST_MINOR=9.6 LATEST=true

before_install:
  - sudo apt-get update -y --allow-unauthenticated
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" docker-engine

before_script:
  - docker build --force-rm=true --build-arg POSTGRESQL_VERSION=${POSTGRESQL_VERSION} -t deeky666/postgresql:${POSTGRESQL_VERSION} .

  - docker run -d -p 5433:5432 deeky666/postgresql:${POSTGRESQL_VERSION}
  - sleep 5
  - psql -h 127.0.0.1 -p 5433 -U postgres -c "SELECT version()"
  - psql -h 127.0.0.1 -p 5433 -U postgres -c "CREATE DATABASE foo"
  - psql -h 127.0.0.1 -p 5433 -U postgres -l | grep foo > /dev/null

  - if [[ ! -z "$TRAVIS_TAG" && ! -z "$LATEST_MINOR" ]]; then docker tag deeky666/postgresql:${POSTGRESQL_VERSION} deeky666/postgresql:${LATEST_MINOR}; fi
  - if [[ ! -z "$TRAVIS_TAG" && ! -z "$LATEST" ]]; then docker tag deeky666/postgresql:${POSTGRESQL_VERSION} deeky666/postgresql:latest; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [ ! -z "$TRAVIS_TAG" ]; then docker push deeky666/postgresql; fi

script: true

matrix:
  fast_finish: true
