#!/bin/bash
set -eo pipefail

# force postgres to not use the local unix socket (test "external" connectibility)
host="$(hostname --ip-address || echo '127.0.0.1')"

if select="$(/usr/local/pgsql/bin/psql -q -A -t -h $host -c 'SELECT 1')" && [ "$select" = '1' ]; then
	exit 0
fi

exit 1
